// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsounhgqvrelitaqionn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzb3VuaGdxdnJlbGl0YXFpb25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjI0MjMsImV4cCI6MjA3MDkzODQyM30.kBaX8jic7tJ8Sn1-WNrpDgYpFyCsn6iUVoslBZjXYMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});